from graph_txt_files.txt_functions.graph_calculator import *
from graph_txt_files.txt_functions.graph_property_names import *
from graph_txt_files.txt_functions.chromatic_number import *
from graph_txt_files.txt_functions.domination import *
from graph_txt_files.txt_functions.independence_number import *
from graph_txt_files.txt_functions.triameter import *
from graph_txt_files.txt_functions.vertex_cover_number import *
from graph_txt_files.txt_functions.matching_number import *
from graph_txt_files.txt_functions.topological_indicies import *

import graph_txt_files.txt_functions.graph_calculator
import graph_txt_files.txt_functions.graph_property_names
import graph_txt_files.txt_functions.chromatic_number
import graph_txt_files.txt_functions.domination
import graph_txt_files.txt_functions.independence_number
import graph_txt_files.txt_functions.triameter
import graph_txt_files.txt_functions.vertex_cover_number
import graph_txt_files.txt_functions.matching_number
import graph_txt_files.txt_functions.topological_indicies
